build-test:
  image: docker:stable
  stage: deploy
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --build-arg BASE_BACK_URL=$URL_BACK_PROD_VR_AWS -t registry.alt-tools.tech/aquildev/projet-ecole/front:$CI_COMMIT_BRANCH .
    - echo "BASE_BACK_URL is set to: $URL_BACK_PROD_VR_AWS"
    - docker push registry.alt-tools.tech/aquildev/projet-ecole/front:$CI_COMMIT_BRANCH
  rules:
    - when: manual