const fakerAdsList = 
[
    {
        id: 1,
        categorie: "Cours",
        titre: "Skatepark",
        description: "sortie skate park. je peux prêter deux trottinettes.",
        startdate: "2024-06-05",
        starttime: "09:00",
        enddate: "2024-06-05",
        endtime: "16:00",
        attendees: '10',
        city: "Grenoble",
        country: "france",
        address: "",
       imageUrl: "zoo.jpg"
          },
    {
        id: 2,
        categorie: "Sortie",
        titre: "Randonnée en montagne",
        description: "Une randonnée pour découvrir les paysages alpins.",
        startdate: "2024-06-05",
        starttime: "09:00",
        enddate: "2024-06-05",
        endtime: "16:00",
        attendees: '10',
        city: "Grenoble",
        country: "france",
        address: "Rue des Alpes",
       imageUrl: "mountain.png"
    },
    {
        id: 3,
        categorie: "Covoiturage",
        titre: "Trajet vers Paris",
        description: "Covoiturage pour aller à Paris. 3 places disponibles.",
        startdate: "2024-05-25",
        starttime: "08:00",
        enddate: "2024-05-25",
        endtime: "12:00",
        attendees: '3',
        city: "Lyon",
        country: "france",
        address: "Gare de Lyon-Part-Dieu",
       imageUrl: "poolcar.png"
    },
    {
        id: 4,
        categorie: "Cours",
        titre: "Cours de guitare",
        description: "Apprenez les bases de la guitare en quelques semaines.",
        startdate: "2024-07-01",
        starttime: "18:00",
        enddate: "2024-07-01",
        endtime: "19:00",
        attendees: '5',
        city: "Marseille",
        country: "france",
        address: "Rue de la Musique",
       imageUrl: "guitar.png"
    },
    {
        id: 5,
        categorie: "Sortie",
        titre: "Visite du musée",
        description: "Découvrez l'histoire de notre ville avec une visite guidée du musée.",
        startdate: "2024-06-15",
        starttime: "10:00",
        enddate: "2024-06-15",
        endtime: "12:00",
        attendees: '20',
        city: "Bordeaux",
        country: "france",
        address: "Musée de Bordeaux",
       imageUrl: "museum.png"
    },
    {
        id: 6,
        categorie: "Covoiturage",
        titre: "Trajet vers la plage",
        description: "Covoiturage pour une journée à la plage. 4 places disponibles.",
        startdate: "2024-07-20",
        starttime: "08:30",
        enddate: "2024-07-20",
        endtime: "19:00",
        attendees: '4',
        city: "Nice",
        country: "france",
        address: "Place Masséna",
       imageUrl: "beach.png"
    },
    {
        id: 7,
        categorie: "Cours",
        titre: "Atelier de cuisine",
        description: "Apprenez à cuisiner des plats français traditionnels.",
        startdate: "2024-08-10",
        starttime: "15:00",
        enddate: "2024-08-10",
        endtime: "18:00",
        attendees: '8',
        city: "Lille",
        country: "france",
        address: "Rue de la Cuisine",
       imageUrl: "cooking.png"
    },
    {
        id: 8,
        categorie: "Sortie",
        titre: "Cinéma en plein air",
        description: "Projection de films classiques en plein air.",
        startdate: "2024-07-18",
        starttime: "21:00",
        enddate: "2024-07-18",
        endtime: "23:00",
        attendees: '100',
        city: "Nantes",
        country: "france",
        address: "Parc de la Ville",
       imageUrl: "cinema.png"
    },
    {
        id: 9,
        categorie: "Covoiturage",
        titre: "Voyage vers la campagne",
        description: "Covoiturage pour un week-end à la campagne. 2 places disponibles.",
        startdate: "2024-08-03",
        starttime: "07:00",
        enddate: "2024-08-03",
        endtime: "23:00",
        attendees: '100',
        city: "Nantes",
        country: "france",
        address: "Parc de la Ville",
       imageUrl: "cinema.png"
    }
]

// const fakerAdsList = [
//     {
//         id: 1,
//         categorie: "Cours",
//         title: "Skatepark",
//         description: "sortie skate park. je peux prêter deux trottinettes.",
//         startdate: "2024-05-19",
//         starttime: "14:25",
//         enddate: "",
//         endtime: "",
//         attendees: "",
//         city: "poitiers",
//         country: "france",
//         address: "",
//         imageUrl: "zoo.png",
//         comments:
//             [
//                 {
//                     id: 1,
//                     firstname: "Gabriel",
//                     lastname: "Rubio",
//                     message: "Ce message est un test.",
//                     date: "10/07/2024",
//                 },
//                 {
//                     id: 2,
//                     firstname: "María",
//                     lastname: "Moreno",
//                     message: "Ceci est un message de test.",
//                     date: " 25/01/2024",
//                 },
//                 {
//                     id: 3,
//                     firstname: "Enrique",
//                     lastname: "Quesada",
//                     message: "Voici un message de test.",
//                     date: " 29/09/2024",
//                 },
//                 {
//                     id: 4,
//                     firstname: "Teresa",
//                     lastname: "Hernández",
//                     message: "Mon message de test.",
//                     date: "envoyé le 17/05/2024",
//                 },
//             ]
//     },
//     {
//         id: 2,
//         title: "Garde d'enfants",
//         address: "70 rue Pasteur",
//         city: "Valence",
//         postal_code: "26000",
//         lat: "44.951290",
//         lng: "4.900990",
//         start: 'dimanche 17 juillet 14h15',
//         attendees: 2,
//         category: 'childcare',
//         description: "Garde d'enfants pour l'après-midi",
//         imageUrl: 'childcare.png',
//         comments:
//             [
//                 {
//                     id: 1,
//                     firstname: "Laura",
//                     lastname: "Morelo",
//                     message: "Un message est un test.",
//                     date: "envoyé le 22/02/2024",
//                 },
//                 {
//                     id: 2,
//                     firstname: "Eduardo",
//                     lastname: "Restrepo",
//                     message: "Voici mon message de test.",
//                     date: "envoyé le 17/03/2024",
//                 },
//             ]
//     },
//     {
//         id: 3,
//         title: "Sortie collective au zoo",
//         address: "5 rue de la victoire",
//         city: "Tarbes",
//         postal_code: "65000",
//         lat: "43.234192",
//         lng: "0.071030",
//         start: '30/05/2024 10h20',
//         attendees: 4,
//         category: 'events',
//         description: "Sortie découverte au zoo",
//         imageUrl: 'zoo.jpg',
//         comments:
//             [
//                 {
//                     id: 1,
//                     firstname: "Raúl",
//                     lastname: "Duque",
//                     message: "Un petit message de test.",
//                     date: "envoyé le 24/04/2024",
//                 },
//             ]
//     },
//     {
//         id: 4,
//         title: "Soutien en maths",
//         address: "30 av C. de Gaulle",
//         city: "Castres",
//         postal_code: "81100",
//         lat: "43.601580",
//         lng: "2.251310",
//         start: 'di. 12 juin 15h10',
//         attendees: 1,
//         category: 'tutoring',
//         description: "Cours de soutien en maths niveau CM2",
//         imageUrl: 'cours.png',
//         comments:
//             [
//                 {
//                     id: 1,
//                     firstname: "Manuel",
//                     lastname: "Torres",
//                     message: "Voilà ce message de test.",
//                     date: "envoyé le 04/11/2024",
//                 },
//                 {
//                     id: 2,
//                     firstname: "Flavia",
//                     lastname: "Suárez",
//                     message: "Ceci est un message de test.",
//                     date: "envoyé le 25/01/2024",
//                 },
//                 {
//                     id: 3,
//                     firstname: "Javier",
//                     lastname: "Luna",
//                     message: "Et un message de test.",
//                     date: "envoyé le 04/07/2024",
//                 },
//             ]
//         },
//         {
//             id: 5,
//             title: "Covoiturage",
//             address: "18 rue Jean Moulin",
//             city: "Amiens",
//             postal_code: "80000",
//             lat: "49.883440",
//             lng: "2.281520",
//             start: 'samedi 10 mai à 14h30',
//             attendees: 3,
//             category: 'poolcar',
//             description: "Covoiturage pour emmener les enfants à l'école",
//             imageUrl: 'poolcar.png',
//             comments:
//                 [
//                     {
//                         id: 1,
//                         firstname: "Gabriel",
//                         lastname: "Rubio",
//                         message: "Ce message est un test.",
//                         date: "10/07/2024",
//                     },
//                     {
//                         id: 2,
//                         firstname: "María",
//                         lastname: "Moreno",
//                         message: "Ceci est un message de test.",
//                         date: " 25/01/2024",
//                     },
//                     {
//                         id: 3,
//                         firstname: "Enrique",
//                         lastname: "Quesada",
//                         message: "Voici un message de test.",
//                         date: " 29/09/2024",
//                     },
//                     {
//                         id: 4,
//                         firstname: "Teresa",
//                         lastname: "Hernández",
//                         message: "Mon message de test.",
//                         date: "envoyé le 17/05/2024",
//                     },
//                 ]
//         },
//         {
//             id: 6,
//             title: "Garde d'enfants",
//             address: "70 rue Pasteur",
//             city: "Valence",
//             postal_code: "26000",
//             lat: "44.951290",
//             lng: "4.900990",
//             start: 'dimanche 17 juillet 14h15',
//             attendees: 2,
//             category: 'childcare',
//             description: "Garde d'enfants pour l'après-midi",
//             imageUrl: 'childcare.png',
//             comments:
//                 [
//                     {
//                         id: 1,
//                         firstname: "Laura",
//                         lastname: "Morelo",
//                         message: "Un message est un test.",
//                         date: "envoyé le 22/02/2024",
//                     },
//                     {
//                         id: 2,
//                         firstname: "Eduardo",
//                         lastname: "Restrepo",
//                         message: "Voici mon message de test.",
//                         date: "envoyé le 17/03/2024",
//                     },
//                 ]
//         },
//         {
//             id: 7,
//             title: "Sortie collective au zoo",
//             address: "5 rue de la victoire",
//             city: "Tarbes",
//             postal_code: "65000",
//             lat: "43.234192",
//             lng: "0.071030",
//             start: '30/05/2024 10h20',
//             attendees: 4,
//             category: 'events',
//             description: "Sortie découverte au zoo",
//             imageUrl: 'zoo.jpg',
//             comments:
//                 [
//                     {
//                         id: 1,
//                         firstname: "Raúl",
//                         lastname: "Duque",
//                         message: "Un petit message de test.",
//                         date: "envoyé le 24/04/2024",
//                     },
//                 ]
//         },
//         {
//             id: 8,
//             title: "Soutien en maths",
//             address: "30 av C. de Gaulle",
//             city: "Castres",
//             postal_code: "81100",
//             lat: "43.601580",
//             lng: "2.251310",
//             start: 'di. 12 juin 15h10',
//             attendees: 1,
//             category: 'tutoring',
//             description: "Cours de soutien en maths niveau CM2",
//             imageUrl: 'cours.png',
//             comments:
//                 [
//                     {
//                         id: 1,
//                         firstname: "Manuel",
//                         lastname: "Torres",
//                         message: "Voilà ce message de test.",
//                         date: "envoyé le 04/11/2024",
//                     },
//                     {
//                         id: 2,
//                         firstname: "Flavia",
//                         lastname: "Suárez",
//                         message: "Ceci est un message de test.",
//                         date: "envoyé le 25/01/2024",
//                     },
//                     {
//                         id: 3,
//                         firstname: "Javier",
//                         lastname: "Luna",
//                         message: "Et un message de test.",
//                         date: "envoyé le 04/07/2024",
//                     },
//                 ]
//             }, {
//                 id: 9,
//                 title: "Covoiturage",
//                 address: "18 rue Jean Moulin",
//                 city: "Amiens",
//                 postal_code: "80000",
//                 lat: "49.883440",
//                 lng: "2.281520",
//                 start: 'samedi 10 mai à 14h30',
//                 attendees: 3,
//                 category: 'poolcar',
//                 description: "Covoiturage pour emmener les enfants à l'école",
//                 imageUrl: 'poolcar.png',
//                 comments:
//                     [
//                         {
//                             id: 1,
//                             firstname: "Gabriel",
//                             lastname: "Rubio",
//                             message: "Ce message est un test.",
//                             date: "10/07/2024",
//                         },
//                         {
//                             id: 2,
//                             firstname: "María",
//                             lastname: "Moreno",
//                             message: "Ceci est un message de test.",
//                             date: " 25/01/2024",
//                         },
//                         {
//                             id: 3,
//                             firstname: "Enrique",
//                             lastname: "Quesada",
//                             message: "Voici un message de test.",
//                             date: " 29/09/2024",
//                         },
//                         {
//                             id: 4,
//                             firstname: "Teresa",
//                             lastname: "Hernández",
//                             message: "Mon message de test.",
//                             date: "envoyé le 17/05/2024",
//                         },
//                     ]
//             },
//             {
//                 id: 10,
//                 title: "Garde d'enfants",
//                 address: "70 rue Pasteur",
//                 city: "Valence",
//                 postal_code: "26000",
//                 lat: "44.951290",
//                 lng: "4.900990",
//                 start: 'dimanche 17 juillet 14h15',
//                 attendees: 2,
//                 category: 'childcare',
//                 description: "Garde d'enfants pour l'après-midi",
//                 imageUrl: 'childcare.png',
//                 comments:
//                     [
//                         {
//                             id: 1,
//                             firstname: "Laura",
//                             lastname: "Morelo",
//                             message: "Un message est un test.",
//                             date: "envoyé le 22/02/2024",
//                         },
//                         {
//                             id: 2,
//                             firstname: "Eduardo",
//                             lastname: "Restrepo",
//                             message: "Voici mon message de test.",
//                             date: "envoyé le 17/03/2024",
//                         },
//                     ]
//             },
//             {
//                 id: 11,
//                 title: "Sortie collective au zoo",
//                 address: "5 rue de la victoire",
//                 city: "Tarbes",
//                 postal_code: "65000",
//                 lat: "43.234192",
//                 lng: "0.071030",
//                 start: '30/05/2024 10h20',
//                 attendees: 4,
//                 category: 'events',
//                 description: "Sortie découverte au zoo",
//                 imageUrl: 'zoo.jpg',
//                 comments:
//                     [
//                         {
//                             id: 1,
//                             firstname: "Raúl",
//                             lastname: "Duque",
//                             message: "Un petit message de test.",
//                             date: "envoyé le 24/04/2024",
//                         },
//                     ]
//             },
//             {
//                 id: 12,
//                 title: "Soutien en maths",
//                 address: "30 av C. de Gaulle",
//                 city: "Castres",
//                 postal_code: "81100",
//                 lat: "43.601580",
//                 lng: "2.251310",
//                 start: 'di. 12 juin 15h10',
//                 attendees: 1,
//                 category: 'tutoring',
//                 description: "Cours de soutien en maths niveau CM2",
//                 imageUrl: 'cours.png',
//                 comments:
//                     [
//                         {
//                             id: 1,
//                             firstname: "Manuel",
//                             lastname: "Torres",
//                             message: "Voilà ce message de test.",
//                             date: "envoyé le 04/11/2024",
//                         },
//                         {
//                             id: 2,
//                             firstname: "Flavia",
//                             lastname: "Suárez",
//                             message: "Ceci est un message de test.",
//                             date: "envoyé le 25/01/2024",
//                         },
//                         {
//                             id: 3,
//                             firstname: "Javier",
//                             lastname: "Luna",
//                             message: "Et un message de test.",
//                             date: "envoyé le 04/07/2024",
//                         },
//                     ]
//                 }
//     ]

/* const AdData = {
    data: fakeAd
} */

export default fakerAdsList;